# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

global:
  evaluation_interval: 30s
  scrape_interval: 5s
scrape_configs:
- job_name: otel-collector
  static_configs:
  - targets:
    - 'otelcol:8888'
- job_name: liatrio-otel-collector
  static_configs:
  - targets:
    - 'liatrio-otelcol:9464'
